# Generated by Django 2.1.3 on 2018-11-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0003_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieManager',
        ),
    ]
