# Generated by Django 2.1.3 on 2018-11-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0004_delete_moviemanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='duration',
            new_name='duration_minutes',
        ),
    ]
