# Generated by Django 2.1.3 on 2018-11-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0005_auto_20181114_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='duration_minutes',
            new_name='duration',
        ),
    ]
