# Generated by Django 2.1.3 on 2018-11-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0007_auto_20181116_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user',
            new_name='user_profile',
        ),
    ]
